 version: "3.8"

 services:
  db:
    container_name: "workout_db"
    image: "postgres:latest"
    volumes:
      - "./database/postgres-data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "workout_user"
      POSTGRES_PASSWORD: "workout_password"
      POSTGRES_DB: "workout_db"  
    restart: unless-stopped  
  test_db:
    container_name: "workout_db_test"
    image: "postgres:latest"
    volumes:
      - "./database/postgres-test-data:/var/lib/postgresql/data:rw"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "workout_user"
      POSTGRES_PASSWORD: "workout_password"
      POSTGRES_DB: "workout_db"  
    restart: unless-stopped
